version: '3'
services: 
  php-server:
    #image: php:7.4.1-apache      # nome da imagem no docker hub
    build: 
      context: ./docker
      dockerfile: Dockerfile
    image: php-custom-server     # imagem personalizada
    volumes: 
      - ./project:/var/www/html/ # pega o projeto e copia para a imagem
    ports: 
      - "80:80"                  # porta 80 da maquina local ouve a porta da imagem  
    links: 
      - db                       # ligacao do php-custom-server com o db

  db: 
    image: mysql:5.6
    ports: 
      - "3306:3306"
    environment: 
      - MYSQL_ROOT_HOST=%       # define 'localhost' como padrao
      - MYSQL_DATABASE=banco-mysql
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes: 
      - ./docker/mysql_volume:/var/lib/mysql # salva os dados do banco